name: Build App
run-name: ${{ github.actor }} is testing out CI
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:


    
    - uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: 6.0.x
          
    - uses: actions/cache@v3
      with:
          path:  ~/.nuget/packages 
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} #hash of project files
          restore-keys: |
            ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run:  dotnet restore VeloTest.sln 

    - name: List files in the repository
      run: |
        ls '~/.nuget/packages'
        
    - name: Install vpk
      run:  dotnet tool install -g vpk

    - name: Build
      run: dotnet build VeloTest.sln  --no-restore
        
    - name: Test
      run: dotnet test VeloTest.sln  --no-build --verbosity normal
      
    - name: Publish
      run: | 
        dotnet publish VeloTest.sln -c Release --no-restore -o publish 


    - name: Sign Package
      run: |
          dotnet build -t:vpk

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: services
        path: Releases
        if-no-files-found: error 
    
     
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is now running on a ${{ runner.os }} server."
    - run: echo "Workspace ${{ github.workspace }}."
    - name: List files in the repository
      run: |
        ls '~/.nuget/packages'
    - run: echo "This job's status is ${{ job.status }}."

